Web.SurveySystem/Controllers/DirectoryController.cs
using System.Web.Mvc;
using BLL.SurveySystem.Interfaces;

namespace Web.SurveySystem.Controllers
{
    [RoutePrefix("directories")]
    [Authorize]
    public class DirectoryController : Controller
    {
        private readonly ILoggerService<DirectoryController> loggingService;
        public DirectoryController(ILoggerService<DirectoryController> loggingService)
        {
            this.loggingService = loggingService;
        }

        [HttpGet]
        [Authorize]
        [Route("directory")]
        public ActionResult Index()
        {
            if (this.User.IsInRole("user"))
            {
                loggingService.Error($"{User.Identity.Name}  go to -> ReferenceDirectory");
                return RedirectToAction("Forbidden", "Error");
            }
            return View();
        }
    }
}

Web.SurveySystem/Controllers/ParameterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using BLL.SurveySystem.DTO;
using BLL.SurveySystem.Infrastructure;
using BLL.SurveySystem.Interfaces;
using Microsoft.AspNet.Identity;
using Web.SurveySystem.Helpers;
using Web.SurveySystem.Models.ViewModels;

namespace Web.SurveySystem.Controllers
{
    [Authorize]
    [RoutePrefix("parameter")]
    public class ParameterController : Controller
    {
        private readonly IParameterService paramService;
        private readonly ILoggerService<ParameterController> loggingService;

        public ParameterController(IParameterService paramService, ILoggerService<ParameterController> loggingService)
        {
            this.paramService = paramService;
            this.loggingService = loggingService;
        }

        [HttpGet]
        [Route("index")]
        public ActionResult Index()
        {
            if (this.User.IsInRole("user"))
            {
                loggingService.Error($"{User.Identity.Name}  go to -> Parameter");
                return RedirectToAction("Forbidden", "Error");
            }
            return View();
        }

        [HttpGet]
        [Authorize]
        [Route("edit/{id}/{tabId?}")]
        public async Task<ActionResult> ParameterDetails(Guid id, int? tabId = 0)
        {
            if (id == Guid.Empty)
                return RedirectToAction("NotFound", "Error");

            var param = await paramService.GetByIdAsync(id);
            if (param != null)
            {
                ViewBag.ParameterId = param.ParameterId;
                ViewBag.CriterionId = param.CriterionId;
                ViewBag.CurrentUserId = User.Identity.GetUserId();
                ViewBag.TabId = tabId > 0 ? tabId : 0;
            }
            else
            {
                return RedirectToAction("NotFound", "Error");
            }
            return View("Details");
        }

        [HttpGet]
        [Authorize]
        [Route("byid")]
        public async Task<JsonNetResult> GetById(Guid id)
        {
            try
            {
                if (id == Guid.Empty)
                {
                    return JsonNetResult.Warn("Неверный идентификатор / Invalid identifier");
                }
                var chart = await paramService.GetByIdAsync(id);
                var mapper = MapperConfigVm.MapperConfigAll();
                var parVm = mapper.Map<ParameterDTO, ParameterVM>(chart);
                return new JsonNetResult(new { success = true, data = parVm });
            }
            catch (Exception e)
            {
                var user = User.Identity.GetUserName();
                loggingService.Error($"User: {user} - {e.Message}");
                return JsonNetResult.Warn(e.Message);
            }
        }

        [HttpGet]
        [Route("all")]
        public async Task<JsonNetResult> GetParameters()
        {
            try
            {
                var paramDto = await paramService.GetAllAsync();
                var mapper = MapperConfigVm.MapperConfigAll();
                var par = mapper.Map<IEnumerable<ParameterDTO>, List<ParameterVM>>(paramDto);
                return new JsonNetResult(new {success = true, data = par });
            }
            catch (Exception e)
            {
                var user = User.Identity.GetUserName();
                loggingService.Error($"User: {user} - {e.Message}");
                return JsonNetResult.Warn(e.Message);
            }
        }

        [HttpPost]
        [Route("active")]
        public async Task<JsonNetResult> GetActiveCriterions(List<FilterModels> filterModels)
        {
            try
            {
                var crit = await paramService.FindByFilterAsync(filterModels);
                var mapper = MapperConfigVm.MapperConfigAll();
                var resVm = mapper.Map<IEnumerable<ParameterDTO>, List<ParameterVM>>(crit);
                return new JsonNetResult(new {success = true, data = resVm});
            }
            catch (Exception e)
            {
                var user = User.Identity.GetUserName();
                loggingService.Error($"GetActive: User: {user} - {e.Message}");
                return JsonNetResult.Warn(e.Message);
            }
        }

        [HttpPost]
        [Authorize(Roles = "admin, manager")]
        [Route("edit")]
        public async Task<JsonNetResult> Update(ParameterVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var config = new MapperConfiguration(c =>
                    {
                        c.CreateMap<ParameterVM, ParameterDTO>()
                            .ForMember(s => s.Indicators, map => map.Ignore())
                            .ForMember(s => s.Criterion, map => map.Ignore());
                    });
                    config.AssertConfigurationIsValid();
                    var mapper = config.CreateMapper();
                    var modelDto = mapper.Map<ParameterVM, ParameterDTO>(model);
                    var update = await paramService.UpdateAsync(modelDto);
                    return new JsonNetResult(new {success = update.Succedeed, message = update.Message});
                }
                else
                {
                    var listErrors = string.Join("<br/>",
                        ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage));
                    loggingService.Error(listErrors);
                    return JsonNetResult.Warn(listErrors);
                }
            }
            catch (Exception e)
            {
                loggingService.Error($"Update: {e.Message}");
                return JsonNetResult.Failure(e.Message);
            }
        }

        [HttpPost]
        [Authorize(Roles = "admin, manager")]
        [Route("add")]
        public async Task<JsonNetResult> Create(ParameterVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var user = User.Identity.GetUserName();
                    var config = new MapperConfiguration(c =>
                    {
                        c.CreateMap<ParameterVM, ParameterDTO>()
                            .ForMember(x => x.ParameterId, m => m.MapFrom(s => Guid.NewGuid()))
                            .ForMember(x => x.CreatedOn, x => x.MapFrom(m => DateTime.Now))
                            .ForMember(x => x.CreatedBy, x => x.MapFrom(m => user))
                            .ForMember(s => s.Indicators, map => map.Ignore())
                            .ForMember(s => s.Criterion, map => map.Ignore());
                    });
                    config.AssertConfigurationIsValid();
                    var mapper = config.CreateMapper();
                    var modelDto = mapper.Map<ParameterVM, ParameterDTO>(model);
                    var update = await paramService.CreateAsync(modelDto);
                    return new JsonNetResult(new {success = update.Succedeed, message = update.Message});
                }
                else
                {
                    var listErrors = string.Join("<br/>",
                        ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage));
                    loggingService.Error(listErrors);
                    return JsonNetResult.Warn(listErrors);
                }
            }
            catch (Exception e)
            {
                loggingService.Error($"{e.Message}");
                return JsonNetResult.Failure(e.Message);
            }
        }

        [HttpPost]
        [Authorize(Roles = "admin, manager")]
        [Route("remove")]
        public async Task<JsonNetResult> Delete(Guid id)
        {
            try
            {
                var user = User.Identity.GetUserName();
                if (id == Guid.Empty)
                {
                    loggingService.Warn($"{user} Parameter Empty Id");
                    return JsonNetResult.Failure("Ошибка удаления / Parameter Empty Id");
                }
                var deleted = await paramService.DeleteAsync(id);
                if (deleted.Succedeed)
                {
                    return JsonNetResult.SuccessMessage(deleted.Message);
                }
                else
                {
                    return JsonNetResult.Failure(deleted.Message);
                }
            }
            catch (Exception e)
            {
                loggingService.Error($"{e.Message}");
                return JsonNetResult.Failure(e.Message);
            }
        }
    }
}

Web.SurveySystem/Views/Parameter/Details.cshtml
@{
    ViewBag.Title = "Показатель / Parameter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts
{
    <script>
        window.ParameterId = '@(ViewBag.ParameterId)';
        window.CriterionId = '@(ViewBag.CriterionId)';
        window.CurrentUserId = '@(ViewBag.CurrentUserId)';
        window.TabPId = '@(ViewBag.TabPId)';
    </script>
    @Scripts.Render("~/Scripts/app/parameter/parameter.details.js")
    @Scripts.Render("~/Scripts/app/parameter/parameter.ind.grid.js")
}

    <div class="row" style="padding: 5px 10px;">
            <div class="form-group col-12 col-sm-12 ml-2">
                <a href="@Url.Action("Index", "Parameter")" class="btn btn-primary btn-sm" title="Вернуться / Backwards"><span class="fa fa-reply"></span> К списку показателей / Back to parameters</a>
            </div>
            <div class="form-group col-12 col-sm-12 col-xl-3 col-md-6">
                <label class="font-weight-bold">Критерий / Criterion</label>
                <input class="form-control" style="min-width: 100%" disabled id="criterionName" placeholder="Критерий / Criterion" />
            </div>
            <div class="form-group col-12 col-sm-12 col-xl-4 col-md-6">
                <label class="font-weight-bold">Показатель / Parameter</label>
                <input class="form-control" style="min-width: 100%" disabled id="paramName" placeholder="Показатель / Parameter" />
            </div>
        </div>
        <div class="form-group col-12" id="divtabIndicators">
            <div id="tabIndic">
                <ul>
                    <li>Индикаторы / Indicators <span id="countIndicators" class="badge badge-secondary badge-pill mr-1 ml-1" style="float: right;">0</span></li>
                </ul>
                <div id="tabIndicators">
                    <div id="gridIndicators" class="mt-3"></div>
                </div>
            </div>
        </div>

Web.SurveySystem/Views/Parameter/Index.cshtml
@{
    ViewBag.Title = "Показатели / Parameters";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts
{
    @Scripts.Render("~/Scripts/app/parameter/parameter.grid.js")
}
<div class="row m-b-5">
    <div class="col-12 col-sm-2">
        <a href="@Url.Action("Index", "Directory")" class="btn btn-link btn-sm"><i class="fa fa-backward" aria-hidden="true"></i> Назад / Backward</a>
    </div>
</div>
<div class="row" style="padding: 15px 5px 5px 5px;">
    <div class="col-12">
        <label class="font-weight-bold" for="gridParameters">Показатели / Parameters</label>
        <div id="gridParameters"></div>
    </div>
</div>