Web.SurveySystem/Controllers/SurveyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using BLL.SurveySystem.DTO;
using BLL.SurveySystem.Infrastructure;
using BLL.SurveySystem.Interfaces;
using IronBarCode;
using Microsoft.AspNet.Identity;
using Web.SurveySystem.Helpers;
using Web.SurveySystem.Models.ViewModels;

namespace Web.SurveySystem.Controllers
{
   
    [RoutePrefix("survey")]
    public class SurveyController : Controller
    {
        private readonly ISurveyService surveyService;
        private readonly IInvitationService invitationService;
        private ILoggerService<SurveyController> loggingService;
        public SurveyController(ISurveyService surveyService, IInvitationService invitationService, ILoggerService<SurveyController> loggingService)
        {
            this.surveyService = surveyService;
            this.invitationService = invitationService;
            this.loggingService = loggingService;
        }

        [HttpGet]
        [Authorize]
        [Route("list")]
        public ActionResult Index()
        {
            if (this.User.IsInRole("user"))
            {
                loggingService.Error($"{User.Identity.Name}  go to -> Survey");
                return RedirectToAction("Forbidden", "Error");
            }
            return View();
        }

        [HttpGet]
        [Authorize]
        [Route("all")]
        public async Task<JsonNetResult> GetSurveys()
        {
            try
            {
                var surveysDto = await surveyService.GetAllAsync();
                var mapper = MapperConfigVm.MapperConfigAll();
                var surveys = mapper.Map<IEnumerable<SurveyDTO>, List<SurveyVM>>(surveysDto);
                return new JsonNetResult(new { success = true, data = surveys });
            }
            catch (Exception e)
            {
                var user = User.Identity.GetUserName();
                loggingService.Error($"User: {user} - {e.Message}");
                return JsonNetResult.Warn(e.Message);
            }
        }

        [HttpPost]
        [Authorize]
        [Route("active")]
        public async Task<JsonNetResult> GetActiveSurveys(List<FilterModels> filterModels)
        {
            try
            {
                var surveys = await surveyService.FindByFilterAsync(filterModels);
                var mapper = MapperConfigVm.MapperConfigAll();
                var resVm = mapper.Map<IEnumerable<SurveyDTO>, List<SurveyVM>>(surveys);
                return new JsonNetResult(new { success = true, data = resVm });
            }
            catch (Exception e)
            {
                var user = User.Identity.GetUserName();
                loggingService.Error($"GetActive: User: {user} - {e.Message}");
                return JsonNetResult.Warn(e.Message);
            }
        }

        [HttpPost]
        [Authorize(Roles = "admin, manager")]
        [Route("edit")]
        public async Task<JsonNetResult> Update(SurveyVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var config = new MapperConfiguration(c =>
                    {
                        c.CreateMap<SurveyVM, SurveyDTO>()
                            .ForMember(s => s.SurveyType, map => map.Ignore())
                            .ForMember(s => s.Invitations, map => map.Ignore())
                            .ForMember(s => s.Questions, map => map.Ignore());
                    });
                    config.AssertConfigurationIsValid();
                    var mapper = config.CreateMapper();
                    var modelDto = mapper.Map<SurveyVM, SurveyDTO>(model);
                    var update = await surveyService.UpdateAsync(modelDto);
                    return new JsonNetResult(new { success = update.Succedeed, message = update.Message });
                }
                else
                {
                    var listErrors = string.Join("<br/>", ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage));
                    loggingService.Error(listErrors);
                    return JsonNetResult.Warn(listErrors);
                }
            }
            catch (Exception e)
            {
                loggingService.Error($"Update Survey: {e.Message}");
                return JsonNetResult.Failure(e.Message);
            }
        }

        [HttpGet]
        [Authorize]
        [Route("edit/{id}/{tabId?}")]
        public async Task<ActionResult> SurveyByCode(int id, int? tabId = 0)
        {
            if (id <= 0)
                return RedirectToAction("NotFound", "Error");

            var survey = await surveyService.GetByCodeAsync(id);
            if (survey != null)
            {
                ViewBag.SurveyId = survey.SurveyId;
                ViewBag.SurveyCode = survey.SurveyCode;
                ViewBag.CurrentUserId = this.User.Identity.GetUserId();
                ViewBag.TabId = tabId > 0 ? tabId : 0;
                ViewBag.IsActive = survey.IsActive && survey.Invitations.All(x=>!x.IsAccepted);
                if (survey.IsAnonymous && !string.IsNullOrEmpty(survey.ShortLink))
                {
                    var genBarCode = QRCodeWriter.CreateQrCode(survey.ShortLink, 100, QRCodeWriter.QrErrorCorrectionLevel.Medium);
                    var imageDataUrl = genBarCode.ToDataUrl();
                    if (!string.IsNullOrWhiteSpace(imageDataUrl))
                    {
                        ViewBag.ImageData = imageDataUrl;
                    }
                }
            }
            else
            {
                return RedirectToAction("NotFound", "Error");
            }
            return View("Details");
        }
        
        [HttpPost]
        [Authorize(Roles = "admin, manager")]
        [Route("add")]
        public async Task<JsonNetResult> Create(SurveyVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var user = User.Identity.GetUserName();
                    var surveyId = Guid.NewGuid();
                    var config = new MapperConfiguration(c =>
                    {
                        c.CreateMap<SurveyVM, SurveyDTO>()
                            .ForMember(x => x.SurveyId, m => m.MapFrom(s => surveyId))
                            .ForMember(x => x.SurveyCode, m => m.MapFrom(s => Math.Abs(surveyId.GetHashCode())))
                            .ForMember(x => x.CreatedOn, x => x.MapFrom(m => DateTime.Now))
                            .ForMember(x => x.CreatedBy, x => x.MapFrom(m => user))
                            .ForMember(s => s.SurveyType, map => map.Ignore())
                            .ForMember(s => s.Questions, map => map.Ignore())
                            .ForMember(s => s.Invitations, map => map.Ignore());
                    });
                    config.AssertConfigurationIsValid();
                    var mapper = config.CreateMapper();
                    var modelDto = mapper.Map<SurveyVM, SurveyDTO>(model);
                    var update = await surveyService.CreateAsync(modelDto);
                    return new JsonNetResult(new { success = update.Succedeed, message = update.Message });
                }
                else
                {
                    var listErrors = string.Join("<br/>", ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage));
                    loggingService.Error(listErrors);
                    return JsonNetResult.Warn(listErrors);
                }
            }
            catch (Exception e)
            {
                loggingService.Error($"{e.Message}");
                return JsonNetResult.Failure(e.Message);
            }
        }

        [HttpPost]
        [Authorize(Roles = "admin, manager")]
        [Route("remove")]
        public async Task<JsonNetResult> Delete(Guid id)
        {
            try
            {
                var user = User.Identity.GetUserName();
                if (id == Guid.Empty)
                {
                    loggingService.Warn($"{user} Survey Empty Id");
                    return JsonNetResult.Failure("Ошибка удаления / Survey Empty Id");
                }

                var deleted = await surveyService.DeleteAsync(id);
                if (deleted.Succedeed)
                {
                    return JsonNetResult.SuccessMessage(deleted.Message);
                }
                else
                {
                    return JsonNetResult.Failure(deleted.Message);
                }
            }
            catch (Exception e)
            {
                loggingService.Error($"{e.Message}");
                return JsonNetResult.Failure(e.Message);
            }
        }
        [HttpGet]
        [Authorize]
        [Route("bycode")]
        public async Task<JsonNetResult> GetByCode(int codeId)
        {
            try
            {
                if (codeId <= 1)
                {
                    return JsonNetResult.Warn("Неверный идентификатор / Invalid identifier");
                }
                var survey = await surveyService.GetByCodeAsync(codeId);
                var mapper = MapperConfigVm.MapperConfigAll();
                var surveyVm = mapper.Map<SurveyDTO, SurveyVM>(survey);

               return new JsonNetResult(new { success = true, data = surveyVm });
            }
            catch (Exception e)
            {
                var user = User.Identity.GetUserName();
                loggingService.Error($"ByCode: User: {user} - {e.Message}");
                return JsonNetResult.Warn(e.Message);
            }
        }


        [HttpGet]
        [Route("start/{id}")]
        public async Task<ActionResult> AnonymousStart(int id)
        {
            if (id <= 0)
                return RedirectToAction("NotFound", "Error");

            var survey = await surveyService.GetByCodeAsync(id);

Web.SurveySystem/Views/Survey/Details.cshtml
@{
    ViewBag.Title = "Карточка теста / Test Card";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="winModEditT"></div>
@section scripts
{
    <script id="winModalSendInvitation" type="text/x-kendo-template">
    <div class="row m-0 p-0">
        <div class="col">
            <label class="font-weight-bold">Приглашение на тест / Invitation on test N <span id="lblNumber" class="text-primary font-italic"></span></label>
        </div>
    </div>
    <div class="row m-0 p-0">
        <div class="col-12">
            <label for="dpTestEnd">Дата завершения / Date of completion</label>
        </div>
        <div class="col-12">
            <input id="dpTestEnd" value="" title="Укажите дату окончания тестирования / Select date of completion" />
        </div>
    </div>
    <div class="row m-0 p-0">
        <div class="col">
            <label>Выберите сотрудников / Select employees</label>
        </div>
        <div class="col-12">            
             <select id="multiSelectUsers" multiple="multiple"></select>
             <span id="lbCountUser" style="float:right; font-size:10pt">Выбрано / Selected: <span id="countUser">0</span></span>            
        </div>
    </div>
    <div class="row mt-0 mr-0 ml-0">
        <div class="form-group col-12 col-md-6">
            <button type="button" onclick="closeWinModalEdT()" class="btn btn-danger btn-block"><span class="fa fa-times"></span> Закрыть / Close</button>
        </div>
        <div class="form-group col-12 col-md-6">
            <button type="button" id="sendInvitationBtn" class="btn btn-success btn-block"><span class="fa fa-paper-plane"></span> Отправить / Send</button>
        </div>
     </div>
</script>
<script>
        window.SurveyId = '@(ViewBag.SurveyId)';
        window.SurveyCode = '@(ViewBag.SurveyCode)';
        window.CurrentUserId = '@(ViewBag.CurrentUserId)';
        window.TabPId = '@(ViewBag.TabPId)';
        window.IsActiveSurvey = @(Json.Encode(ViewBag.IsActive ?? false));
</script>
    @Scripts.Render("~/Scripts/app/survey/survey.details.js")
    @Scripts.Render("~/Scripts/app/survey/survey.questions.grid.js")
    @Scripts.Render("~/Scripts/app/survey/survey.invitations.grid.js")
}
<style>
    .selected {
        background-color: #add8e6;
    }
</style>

<div class="row" style="padding: 5px;">
    <div class="form-group col-12 col-sm-12 ml-2">
        <a href="@Url.Action("Index", "Survey")" class="btn btn-primary btn-sm" title="Вернуться к списку тестов / Back to test list"><span class="fa fa-reply"></span> Назад / Back</a>
    </div>
</div>
<script type="text/x-kendo-template" id="headerStartSurvey">
<div class="form-group row info">
    <fieldset class="col-xs-12 col-sm-12" style="border: 2px solid; width: 10px">
        <legend style="font-size:22px;">Тест #=data.SurveyCode# / Test #=data.SurveyCode#</legend>
        <table class="table" style=" width: 100%;">               
            <tr>
                <th>Название теста / Test Name</th>
                <th>Тип теста / Test Type</th>
                @*<th min-width="50%">Цель / Purpose</th>*@
                <th>Время / Est.time</th>
                <th>Опрос / Survey</th>
                <th>Анон. / Is Anon</th>
                @if (ViewBag.ImageData != null)
                {
                    <th>Код / QR</th>
                }
            </tr>
            <tr>
                <td width="30%"><span class="label label-info">#=data.NameRus# / #=data.NameEng#</span></td>
                <td width="20%"><span class="label label-info">#=data.SurveyType.FullName#</span></td>
                @*<td><span class="label label-info">#=data.PurposeRus# / #=data.PurposeEng#</span></td>*@
                <td width="10%"><span class="label label-info"> #=data.TimeEstimateMin#</span></td>
                <td width="10%"> <input type="checkbox" #=data.IsSurvey ? "checked=checked" : "" # disabled="disabled" /></td>
                <td width="10%"> <input type="checkbox" #=data.IsAnonymous ? "checked=checked" : "" # disabled="disabled" /></td>
                 @if (@ViewBag.ImageData != null)
                 {
                     <td width="10%"> <img alt="" id="imgQr" src="@ViewBag.ImageData"  width="30%"></td>
                 }
            </tr>
        </table>
    </fieldset>
</div>
</script>
<div class="row">
    <div class="col">
        <div id="contentStartUser" class="ml-4 mr-4"></div>
    </div>
</div>

<div class="form-group  col-12" id="divtabSurveys">
    <div id="tabSurvey">
        <ul>
            <li>Список вопросов / Question List <span id="countQuestions" class="badge badge-secondary badge-pill mr-1 ml-1" style="float: right;">0</span></li>
            @if (this.User.IsInRole("admin") || this.User.IsInRole("manager"))
            {
                <li class="k-state-active">Приглашения / Invitations <span id="countInvitations" class="badge badge-secondary badge-pill mr-1 ml-1" style="float: right;">0</span></li>
            }
        </ul>
        <div id="tabQuestions">
            <div id="gridQuestions" class="mt-3"></div>
        </div>
        @if (this.User.IsInRole("admin") || this.User.IsInRole("manager"))
        {
            <div id="tabInvitations">
                <div id="gridInvitations" class="mt-3"></div>
            </div>
        }
    </div>
</div>

Web.SurveySystem/Views/Survey/Index.cshtml
@{
    ViewBag.Title = "Анкеты / Surveys";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts
{
    @Scripts.Render("~/Scripts/app/survey/survey.grid.js")
    <script id="winModalSendInvitation" type="text/x-kendo-template">
        <div class="row m-0 p-0">
            <div class="col">
                <label class="font-weight-bold">Приглашение на тест / Invitation on test N <span id="lblNumber" class="text-primary font-italic"></span></label>
            </div>
        </div>
        <div class="row m-0 p-0">
            <div class="col-12">
                <label for="dpTestEnd">Дата завершения / Date of completion</label>
            </div>
            <div class="col-12">
                <input id="dpTestEnd" value="" title="Укажите дату окончания тестирования / Select date of completion" />
            </div>
        </div>
        <div class="row m-0 p-0">
            <div class="col">
                <label>Выберите сотрудников / Select employees</label>
            </div>
            <div class="col-12">
                <select id="multiSelectUsers" multiple="multiple"></select>
                <span id="lbCountUser" style="float:right; font-size:10pt">Выбрано / Selected: <span id="countUser">0</span></span>
            </div>
        </div>
        <div class="row mt-0 mr-0 ml-0">
            <div class="form-group col-12 col-md-6">
                <button type="button" onclick="closeWinModalEdT()" class="btn btn-danger btn-block"><span class="fa fa-times"></span> Закрыть / Close</button>
            </div>
            <div class="form-group col-12 col-md-6">
                <button type="button" id="sendInvitationBtn" class="btn btn-success btn-block"><span class="fa fa-paper-plane"></span> Отправить / Send</button>
            </div>
        </div>
    </script>
}
<div id="winModEditT"></div>
<label class="font-weight-bold" for="gridSurveys">Анкеты / Surveys</label>
<div class="row" style="padding: 0 15px 15px 15px;">
    <div class="card col-12 border-primary">
        <div class="card-body pt-3 pb-2">
            <div class="form-group has-search mb-0" title="Введите параметры для поиска / Input search parameters">
                <span class="fa fa-search form-control-feedback"></span>
                <span id="clearSearchSurvey" class="fa fa-times-circle form-control-clear" style="display: none;" title="Очистить / Clear"></span>
                <input type="text" id="txtSearchSurvey" class="form-control" autofocus placeholder="Введите параметры для поиска / Input search parameters" value="">
            </div>
            <spam class="text-success font-weight-bold font-italic small ml-3"> Поиск возможен от 2-х символов / Search is possible from 2 characters</spam>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div id="gridSurveys"></div>
    </div>
</div>