Web.SurveySystem/Controllers/DirectoryController.cs
using System.Web.Mvc;
using BLL.SurveySystem.Interfaces;

namespace Web.SurveySystem.Controllers
{
    [RoutePrefix("directories")]
    [Authorize]
    public class DirectoryController : Controller
    {
        private readonly ILoggerService<DirectoryController> loggingService;
        public DirectoryController(ILoggerService<DirectoryController> loggingService)
        {
            this.loggingService = loggingService;
        }

        [HttpGet]
        [Authorize]
        [Route("directory")]
        public ActionResult Index()
        {
            if (this.User.IsInRole("user"))
            {
                loggingService.Error($"{User.Identity.Name}  go to -> ReferenceDirectory");
                return RedirectToAction("Forbidden", "Error");
            }
            return View();
        }
    }
}

Web.SurveySystem/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using BLL.SurveySystem.DTO;
using BLL.SurveySystem.Interfaces;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using Web.SurveySystem.Helpers;
using Web.SurveySystem.Models.ViewModels;

namespace Web.SurveySystem.Controllers
{
    [RoutePrefix("users")]
    public class UserController : Controller
    {
        private readonly IUserService userService;
        private readonly IRoleService roleService;
        private readonly ILoggerService<UserController> loggingService;

        public UserController(ILoggerService<UserController> logServ, IRoleService roleService, IUserService userService)
        {
            this.loggingService = logServ;
            this.userService = userService;
            this.roleService = roleService;
        }
        private IAuthenticationManager AuthenticationManager => HttpContext.GetOwinContext().Authentication;

        // GET: ManagerUser
        [HttpGet]
        [Authorize]
        [Route("index")]
        public ActionResult Index()
        {
            if (!User.IsInRole("admin") && !User.IsInRole("manager"))
            {
                loggingService.Error("Access is denied");
                return RedirectToAction("Forbidden", "Error");
            }
            return View();
        }

        [HttpGet]
        [Authorize]
        [Route("edit/{id}")]
        public async Task<ActionResult> Edit(Guid id)
        {
            if (id == Guid.Empty)
            {
                loggingService.Error("User edit guid empty");
                return RedirectToAction("Forbidden", "Error");
            }
            //Если обычный user, берем его Id
            if (!User.IsInRole("admin") && !User.IsInRole("manager"))
            {
                if (!Guid.TryParse(User.Identity.GetUserId(), out id))
                {
                    loggingService.Error("UserId Invalid");
                    return RedirectToAction("Forbidden", "Error");
                }
            }
            var user = await userService.GetUserById(id.ToString());
            if (user == null)
            {
                loggingService.Error("User edit guid empty");
                return RedirectToAction("Forbidden", "Error");
            }
            ViewBag.UserId = id;
            return View("Edit");
        }

        [HttpGet]
        [Authorize]
        [Route("user")]
        [OutputCache(Duration = 30, Location = OutputCacheLocation.Downstream)]
        public async Task<JsonNetResult> GetUserById(Guid id)
        {
            try
            {
                if (id == Guid.Empty)
                {
                    loggingService.Error("User edit guid empty");
                    return JsonNetResult.Warn("Отсутствует Id / UserId empty");
                }
                if (!User.IsInRole("admin") && !User.IsInRole("manager") && !User.IsInRole("hr"))
                {
                    if (!Guid.TryParse(User.Identity.GetUserId(), out id))
                    {
                        loggingService.Error("User edit guid empty");
                        return JsonNetResult.Warn("Отсутствует Id / UserId empty");
                    }
                }
                var user = await userService.GetUserById(id.ToString());
                if (user == null)
                {
                    loggingService.Error("User not found in DataBase");
                    return JsonNetResult.Warn("Пользователь не найден / User not found");
                }
                var result = new UserVM
                {
                    Id = Guid.TryParse(user.Id, out id) ? id : Guid.Empty,
                    Email = user.Email,
                    Name = user.DisplayName,
                    IsTwoFactor = user.TwoFactorEnabled,
                    IsExternal = user.IsExternal,
                    IsLockoutEnabled = user.LockoutEnabled,
                    Roles = user.Roles != null && user.Roles.Any()
                            ? user.Roles.Select(r => new RoleVM
                            {
                                Id = r.RoleId,
                                Name = string.Empty
                            }).ToList()
                            : null
                };
                return new JsonNetResult(new { success = true, data = result });
            }
            catch (Exception e)
            {
                loggingService.Error($"GetUsers: {e.Message}");
                return JsonNetResult.Failure(e.Message);
            }
        }

        [HttpPost]
        [Authorize]
        [OutputCache(Duration = 30, Location = OutputCacheLocation.Downstream)]
        [Route("find")]
        public async Task<JsonNetResult> GetDomainUsers(string searchtxt)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(searchtxt))
                {
                    var users = (await userService.GetUsers()).Where(y => !string.IsNullOrEmpty(y.UserName)
                                                                                && !string.IsNullOrEmpty(y.Email))
                        .Select(x => new UserVM
                        {
                            Id = Guid.TryParse(x.Id, out var id) ? id : Guid.Empty,
                            Email = x.Email.Trim(),
                            Name = string.Concat(x.DisplayName, " (", x.Email.Substring(x.Email.IndexOf("@", StringComparison.Ordinal) + 1), ")"),
                            IsExternal = x.IsExternal
                        }).ToList();
                    return new JsonNetResult(new { success = true, data = users.DistinctBy(u => u.Email).OrderBy(x => x.Name).ToList() });
                }
                //Guid
                else if (!string.IsNullOrEmpty(searchtxt) && HelperVm.IsGuid(searchtxt))
                {
                    if (!Guid.TryParse(searchtxt, out var id))
                        return JsonNetResult.Warn("Пользователь не найден");
                    var resUser = await userService.GetDomainUserById(id);
                    if (resUser == null)
                        return JsonNetResult.Warn("Пользователь не найден");
                    var us = new List<UserVM>
                    {
                        new UserVM {
                            Id = Guid.TryParse(resUser.Id, out var _id) ? _id : Guid.Empty,
                            Email = string.IsNullOrEmpty(resUser.Email) ? string.Empty : resUser.Email.Trim(),
                            Name = string.Concat(resUser.DisplayName, " (",resUser.Email.Substring(resUser.Email.IndexOf("@", StringComparison.Ordinal) + 1),")"),
                            IsExternal = resUser.IsExternal
                        }
                    };
                    return new JsonNetResult(new { success = true, data = us });
                }
                //Text
                else if (!string.IsNullOrEmpty(searchtxt) && ! HelperVm.IsGuid(searchtxt))
                {
                    var resUser = (await userService.GetDomainUsersByNameList(searchtxt.Trim()))
                        .Select(x => new UserVM
                        {
                            Id = Guid.TryParse(x.Id, out var id) ? id : Guid.Empty,
                            Email = x.Email.Trim(),
                            IsExternal = x.IsExternal,
                            Name = string.Concat(x.DisplayName, " (", x.Email.Substring(x.Email.IndexOf("@", StringComparison.Ordinal) + 1), ")")
                        }).ToList();
                    return new JsonNetResult(new { success = true, data = resUser.DistinctBy(u => u.Email).OrderBy(x => x.Name).ToList() });
                }
                return JsonNetResult.Warn("Уточните параметры поиска / Refine your search");
            }
            catch (Exception e)
            {
                loggingService.Error($"GetUserToRole: {e.Message}");
                return JsonNetResult.Failure(e.Message);
            }
        }

        [HttpPost]
        [Authorize]
        [Route("save")]
        public async Task<JsonNetResult> UpdateAsync(UserVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (string.IsNullOrEmpty(model.Id.ToString()) || !HelperVm.IsGuid(model.Id.ToString()))
                    {
                        return JsonNetResult.Warn("Идентификатор сотрудника недействителен / Employee ID is not correct.");
                    }

                    if (User.IsInRole("admin") || User.IsInRole("manager"))
                    {
                        if (model.Roles == null || !model.Roles.Any())
                        {
                            return JsonNetResult.Warn("Выберите роль / Select role");
                        }
                    }

                    var userModel = new ApplicationUserDTO
                    {
                        DisplayName = model.Name,
                        Id = model.Id.ToString(),
                        Email = model.Email
                    };
                    var update = await userService.UpdateUserAsync(userModel);
                    if (update.Succedeed)
                    {
                        //Обновляем роли
                        if (model.Roles != null && model.Roles.Any())
                        {
                            //Удаляем все роли у пользователя
                            var deleteRoles = await roleService.DeleteUserAllRolesAsync(model.Id.ToString());
                            if (!deleteRoles.Succedeed)
                            {
                                return JsonNetResult.Warn(deleteRoles.Message);
                            }
                            //Добавляем вновь
                            foreach (var role in model.Roles)

Web.SurveySystem/Views/Shared/Navigation.cshtml
@using Microsoft.AspNet.Identity
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">
    <a class="navbar-brand mr-1" href="@Url.Action("Index", "Home")" title="☢️ Система анкетирования">
        <img src="~/Content/images/logo.png" class="img-fluid" alt="Система анкетирования" />
    </a>
    <button class="btn btn-light btn-sm d-inline d-sm-none order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
    <div class="input-group"></div>
    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
        @if (Request.IsAuthenticated)
        {
            <li class="nav-item dropdown no-arrow mx-2">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-circle fa-fw"></i>
                    @User.Identity.GetUserName()
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    @if (!ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
                    {
                    <a class="dropdown-item" href="@Url.Action("Edit", "User", new {id = @User.Identity.GetUserId()})" title="Личные данные / Employee card"><i class="fa fa-id-badge"></i> Employee card</a>
                    }
                    <div class="dropdown-divider m-0"></div>
                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                    {
                        <a class="dropdown-item" href="#" title="👋 Выход/Logout" onclick="document.getElementById('logoutForm').submit()" data-toggle="modal" data-target="#logoutModal"><i class="fas fa-sign-out-alt badge-danger"></i> Выход / Logout</a>
                    }
                </div>
            </li>
        }
        else
        {
            <li class="nav-item dropdown no-arrow mx-2">
                <a class="nav-link dropdown-toggle" href="@Url.Action("Login", "Account")" title="Вход / Login"><i class="fas fa-sign-in-alt"></i> Вход / Login</a>
            </li>
        }
    </ul>
</nav>

Web.SurveySystem/Views/Shared/Sidebar.cshtml
@if (Request.IsAuthenticated)
{<div id="layoutSidenav_nav">
        <!-- Sidebar -->
        <ul class="sidebar navbar-nav toggled">
            <li class="nav-item border border-secondary border-top-0 border-right-0 border-left-0">
                <a class="nav-link" href="@Url.Action("Index", "Home")" title="🏠 Главная / Home">
                    <i class="fa fa-home"></i>
                    <span>Главная <br /> Home</span>
                </a>
            </li>
            @if (this.User.IsInRole("user"))
            {
            <li class="nav-item d-none d-md-inline-block border border-secondary border-top-0 border-right-0 border-left-0">
                <a class="nav-link" href="@Url.Action("Index", "Invitation")" title="📝 Мои тесты / My Tests">
                    <i class="fas fa-fw fa-file"></i>
                    <span>Мои тесты<br />My Tests</span>
                </a>
            </li>
            }
            else if (this.User.IsInRole("admin") || this.User.IsInRole("manager"))
            {
                <li class="nav-item d-none d-md-inline-block border border-secondary border-top-0 border-right-0 border-left-0">
                    <a class="nav-link" href="@Url.Action("Index", "Invitation")" title="📝 Мои тесты / My Tests">
                        <i class="fas fa-fw fa-file"></i>
                        <span>Мои тесты<br />My Tests</span>
                    </a>
                </li>
                <li class="nav-item border border-secondary d-none d-md-inline-block border-top-0 border-right-0 border-left-0">
                    <a class="nav-link" href="@Url.Action("Index", "Survey")" title="☑ Тесты / Tests">
                        <i class="fas fa-fw fa-database"></i>
                        <span>Тесты<br />Test List</span>
                    </a>
                </li>
                <li class="nav-item d-none d-md-inline-block border border-secondary border-top-0 border-right-0 border-left-0">
                    <a class="nav-link" href="@Url.Action("Index", "Reports")" title="📊 Аналитика / Analytics">
                        <i class="fas fa-fw fa-chart-area"></i>
                        <span>Аналитика<br />Analytics</span>
                    </a>
                </li>
                <li class="nav-item d-none d-md-inline-block border border-secondary border-top-0 border-right-0 border-left-0">
                    <a class="nav-link" href="@Url.Action("Index", "Directory")" title="📂 Справочники / Directories">
                        <i class="fas fa-fw fa-folder"></i>
                        <span>Cправочники<br /> Directories</span>
                    </a>
                </li>
            }
            @*Инструкции*@
            <li class="nav-item dropdown border border-secondary border-top-0 border-right-0 border-left-0">
                <a class="nav-link" href="@Url.Action("Show", "Instruction")" title="⚠️ Инструкции / Instructions">
                    <i class="fa fa-book"></i>
                    <span>Инструкции <br /> Instructions</span>
                </a>
            </li>
        </ul>
    </div>
}

Web.SurveySystem/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@using Newtonsoft.Json
@using Web.SurveySystem.Helpers
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />
    <meta name="description" content="SurveySystem.titan2.ru">
    <meta name="author" content="a.loginov">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/bundles/kendocss")
    @RenderSection("Styles", required: false)
    <!-- Bootstrap core JavaScript-->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    <!-- Core plugin JavaScript-->
    @Scripts.Render("~/bundles/jqueryeasing")
    <!-- Kendo-->
    @Scripts.Render("~/bundles/kendojs")
    <script>
        window.permissions = @Html.Raw(JsonConvert.SerializeObject(new
                        {
                            Edit = @User.IsInRole("admin") || @User.IsInRole("manager"),
                            Delete = @User.IsInRole("admin") || @User.IsInRole("manager"),
                            Add = @User.IsInRole("manager") || @User.IsInRole("admin"),
                            View = @User.IsInRole("user"),
                            CurrentUserId = @User.Identity.GetUserId()
                        }));
    </script>
</head>
<body id="page-top" class="sidebar-toggled">
    <div id="progress" class="myclassselector"></div>
    <div id="winModalInfo"></div>
    @Html.Partial("~/Views/Shared/Navigation.cshtml")
    <div id="wrapper">
        @Html.Partial("~/Views/Shared/Sidebar.cshtml")
        <div id="content-wrapper">
            <div class="container-fluid">
                @RenderBody()
            </div>
            <!-- /.container-fluid -->
            <!-- Sticky Footer -->
            @if (Request.IsAuthenticated)
            {
                <footer class="sticky-footer">
                    <div class="container my-auto">
                        <div class="copyright text-center my-auto text-black">
                            <span class="font-weight-normal font-italic">SurveySystem © Titan2.ru, @DateTime.Now.Year | Все права защищены | All rights reserved | @Html.ApplicationVersion()</span>
                        </div>
                    </div>
                </footer>
            }
        </div>
    </div>
    <span id="popupNotificationEdit"></span>
    <!-- Custom scripts for all pages-->
    @Scripts.Render("~/bundles/theme")
    @RenderSection("scripts", required: false)

</body>
</html>